name: Production Build
on:
  push:
    tags:
      - "v*.*.*"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - name: Check Out Repo
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
          # Defaults to the user or organization that owns the workflow file
          scope: '@nanobox'

      - run: yarn
      - run: yarn build
      - run: yarn test

      - name: Zip Folder
        run: zip -r nano-client.zip * -x src/__tests__

      - name: Release Drafter
        id: release_drafter
        uses: release-drafter/release-drafter@v5
        with:
          name: ${{ steps.package-version.outputs.current-version }}
          tag: v${{ steps.package-version.outputs.current-version }}
          version: ${{ steps.package-version.outputs.current-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release_drafter.outputs.upload_url }} # This pulls ID from the Release Drafter step
          asset_path: nano-client.zip
          asset_name: nano-client.zip
          asset_content_type: application/zip
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

